### ISSUE TITLE
Volume Viewer gets too tall to be displayed

### ISSUE THREAD

**Issue by jjkelu** [fiji/Volume_Viewer#5]
As the title suggested.  The key functions at the bottom of the windows cant be accessed.  No matter how you change the size of the window, it keeps extending itself and eventually becomes so tall that the bottom part of the program extends out of the screen.  Maximising of the windows did not make the program to 'fit'.  Changing of the scaling of the display or the resolution both did not help.  A similar problem was reported elsewhere (https://forum.image.sc/t/fiji-volume-viewer-plugin-window-too-tall-lately-please-help/77799).  

I confirm the software is up to date.  The present version of Fiji ImageJ is 1.53t, Java 1.8.0_172 (64-bit).  This is on a windows 10 home edition 64-bit.  Would you be able to provide a resolution?  Thanks.

*Update: This issue, however, is not present in an older version, i.e, 1.51n, Java 1.8.0_66 (just tested).

**Comment by rasband** [comment]
I found that checking "Automatically hide taskbar" in the taskbar settings helps. Moving the taskbar to the side of the screen would also probably help but there does not seem to be an easy way to do this on Windows 11.

**Comment by jjkelu** [comment]
> I found that checking "Automatically hide taskbar" in the taskbar settings helps. Moving the taskbar to the side of the screen would also probably help but there does not seem to be an easy way to do this on Windows 11.

Thanks for your suggestion.  Yes, I did try.  Unfortunately, it did not help, whenever it saw any extra space, it automatically extended itself to fill the gap and then beyond.  I even tried changing my display from portrait to landscape, which also did not help.  So I think the issue is not about space.  My only way to get around for now is to use an older version of Fiji.

**Comment by rasband** [comment]
The latest Windows distribution of ImageJ at
   https://imagej.net/ij/download.html
includes an updated version of the Volume Viewer (version 2.1) that should work better. You may have to click on the maximize button to see the whole window.

All I did was remove these 5 lines from  Volume_Viewer.java:

```
        frame.addComponentListener(new ComponentAdapter(){
                public void componentResized(ComponentEvent event) {
                    buildFrame();
                }
            });

```

**Comment by jjkelu** [comment]
Thank you so much, problem solved!  Greatly appreciate it.  :)
